'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

type Quote = { id: string; client_code: string; name: string; email: string; company: string | null; service: string; hours: number; description: string | null; budget_calculated: number; status: string; created_at: string }
const statuses = ['recibida','en revisión','presupuesto enviado','aceptada','en curso','completada','cancelada']

export default function AdminPage() {
  const router = useRouter(); const [quotes, setQuotes] = useState<Quote[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [statusFilter, setStatusFilter] = useState('todos')
  async function load() { try { const response = await fetch('/api/admin/quotes', { cache: 'no-store' }); if (response.status === 401) { router.replace('/admin/login'); return } const data = await response.json(); if (!response.ok) setError(data.error || 'Error'); else setQuotes(data.quotes || []) } catch { setError('No se pudo conectar con el panel') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  async function update(id: string, status: string) { const response = await fetch('/api/admin/quotes', { method:'PATCH', headers:{'content-type':'application/json'}, body:JSON.stringify({ id, status }) }); if (!response.ok) setError('No se pudo actualizar'); else setQuotes(rows => rows.map(row => row.id === id ? {...row, status} : row)) }
  async function logout() { await createClient().auth.signOut(); router.replace('/admin/login') }
  const visibleQuotes = quotes.filter(quote => { const value = `${quote.client_code} ${quote.name} ${quote.email} ${quote.service}`.toLowerCase(); return value.includes(query.toLowerCase()) && (statusFilter === 'todos' || quote.status === statusFilter) });
  return <main className="admin-shell min-h-screen px-5 py-12 text-white"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="mono text-xs tracking-[.3em] text-cyan-300">NEOTECH / CONTROL ROOM</p><h1 className="mt-3 text-4xl font-bold">Solicitudes de presupuesto</h1><p className="mt-3 text-slate-400">Panel protegido para revisar y actualizar estados.</p></div><button onClick={logout} className="rounded-lg border border-slate-600 px-4 py-2 text-sm text-slate-300 hover:border-cyan-300">Cerrar sesión</button></div>{error&&<p className="mt-6 rounded-lg border border-amber-400/30 bg-amber-400/10 p-4 text-amber-200">{error}</p>}{!loading&&<div className="mt-8 flex flex-wrap gap-3"><input aria-label="Buscar solicitudes" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por código, cliente o email" className="min-w-[280px] flex-1 rounded border border-cyan-400/20 bg-[#111827] px-3 py-2 text-sm"/><select aria-label="Filtrar por estado" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="rounded border border-cyan-400/20 bg-[#111827] px-3 py-2 text-sm"><option value="todos">Todos los estados</option>{statuses.map(status=><option key={status}>{status}</option>)}</select></div>}{loading?<p className="mt-10 text-slate-400">Cargando solicitudes...</p>:<div className="admin-table mt-10 overflow-x-auto rounded-sm border"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-white/[.05] text-slate-400"><tr>{['Código','Cliente','Servicio','Importe','Fecha','Estado'].map(x=><th key={x} className="px-5 py-4 font-medium">{x}</th>)}</tr></thead><tbody>{visibleQuotes.map(quote=><tr key={quote.id} className="border-t border-white/10"><td className="px-5 py-4 font-mono text-cyan-300">{quote.client_code}</td><td className="px-5 py-4"><strong>{quote.name}</strong><span className="block text-xs text-slate-500">{quote.email}</span></td><td className="px-5 py-4 text-slate-300">{quote.service}</td><td className="px-5 py-4">{quote.budget_calculated}€</td><td className="px-5 py-4 text-slate-400">{new Date(quote.created_at).toLocaleDateString('es-ES')}</td><td className="px-5 py-4"><select value={quote.status} onChange={e=>update(quote.id,e.target.value)} className="rounded border border-cyan-400/20 bg-[#111827] px-3 py-2 text-sm"><option value={quote.status}>{quote.status}</option>{statuses.filter(status=>status!==quote.status).map(status=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table>{quotes.length===0&&<p className="p-8 text-slate-400">No hay solicitudes todavía.</p>}</div>}</div></main>
}
