'use client'

import { FormEvent, useEffect, useState, type ReactNode } from 'react'
import emailjs from '@emailjs/browser'
import jsPDF from 'jspdf'
import { ArrowRight, Check, Code2, ExternalLink, FileDown, Mail, MapPin, Menu, Palette, Phone, Send, Server, ShieldCheck, X } from 'lucide-react'
import { saveQuote } from '@/lib/supabase'

const EMAILJS_PUBLIC_KEY = process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || 'Kes0uwCNdJkfPTi2B'
const EMAILJS_SERVICE_ID = process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || 'service_qs5srkr'
const EMAILJS_TEMPLATE_ID = process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID || 'template_4me8r7g'
const ADMIN_EMAIL = 'larbimhed260796@gmail.com'
const rates: Record<string, number> = { 'Soporte Remoto': 55, 'Soporte Presencial': 75, 'Desarrollo Web': 950, 'Consultoría IT': 85, 'Análisis de Sistemas': 75, 'Plan STARTER': 99, 'Plan PROFESSIONAL': 179, 'Plan ENTERPRISE': 399 }
const projects = [['Ella\'s Details','ellasdetails.netlify.app','Landing e-commerce','Dayton, Ohio','Web para decoraciones y desayunos'],['You Portfolio Danza','youdance.netlify.app','Portfolio','Universidad de Lyon','Sitio trilingüe para bailarina profesional'],['Mariano Patines ZGZ','zgzpatinesnano.netlify.app','Negocio local','Zaragoza','Web con click-to-call para tienda local'],['ASOCEMIR','asocemir.netlify.app','Asociación','Zaragoza / Argentina','Sitio bilingüe para asociación cultural']] as const
const services = [['Soporte Remoto','Asistencia técnica, diagnóstico y optimización','55€','hora',Server],['Soporte Presencial','Instalación y mantenimiento en tu empresa','75€','hora',MapPin],['Desarrollo Web','Webs profesionales y e-commerce básico','950€','desde',Code2],['Consultoría IT','Análisis, planificación y decisiones técnicas','85€','hora',ShieldCheck]] as const
const plans = [['STARTER','99€',['3 horas de soporte al mes','Email y teléfono','Respuesta en 24h']],['PROFESSIONAL','179€',['8 horas de soporte al mes','Una visita presencial','Respuesta en 12h']],['ENTERPRISE','399€',['Soporte prioritario','Visitas incluidas','Consultoría continua']]] as const

function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: ReactNode }) { return <section id={id} className="section"><div className="section-inner"><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children}</div></section> }

function TrackingPanel() { const [code,setCode]=useState(''); const [email,setEmail]=useState(''); const [result,setResult]=useState<{client_code:string;status:string;service:string;created_at:string}|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); async function lookup(e:FormEvent){e.preventDefault();setLoading(true);setError('');setResult(null);try{const r=await fetch(`/api/quotes/lookup?code=${encodeURIComponent(code)}&email=${encodeURIComponent(email)}`);const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo consultar');setResult(data)}catch(err){setError(err instanceof Error?err.message:'No se pudo consultar')}finally{setLoading(false)}} return <section id="seguimiento" className="tracking"><div className="section-inner tracking-grid"><div><p className="eyebrow">Seguimiento</p><h2>Siempre sabes en qué punto está tu solicitud.</h2><p className="lede">Accede con tu cuenta y consulta únicamente tus propios pedidos.</p><a className="text-link" href="/login">Iniciar sesión <ArrowRight size={16}/></a></div><form className="form-card" onSubmit={lookup}><div className="form-grid"><label>Código<input required value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="NT-..." /></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="tu@email.com" /></label></div><button className="button button-primary" disabled={loading}>{loading?'Consultando…':'Consultar estado'}</button>{error&&<p className="form-message error" role="alert">{error}</p>}{result&&<div className="status-card" role="status"><strong>{result.client_code}</strong><span>{result.status}</span><small>{result.service} · {new Date(result.created_at).toLocaleDateString('es-ES')}</small></div>}</form></div></section> }

export default function Home(){
 const [open,setOpen]=useState(false); const [mobile,setMobile]=useState(false); const [service,setService]=useState('Soporte Remoto'); const [status,setStatus]=useState('idle'); const [contactStatus,setContactStatus]=useState('idle'); const [theme,setTheme]=useState<'night'|'light'>('night'); const [booting,setBooting]=useState(true)
 useEffect(()=>{const t=window.setTimeout(()=>setBooting(false),650);return()=>window.clearTimeout(t)},[])
 const quote=(title='Solicitar presupuesto')=>{setService(title);setOpen(true)}
 async function downloadQuote(data:{name:string;email:string;company:string;service:string;hours:number;notes:string;budget:number}){const doc=new jsPDF();doc.setFillColor(11,12,14);doc.rect(0,0,210,297,'F');doc.setTextColor(245,246,243);doc.setFontSize(24);doc.text('NeoTech ZGZ',20,28);doc.setFontSize(11);doc.text('Presupuesto personalizado',20,40);doc.text(`Cliente: ${data.name}`,20,70);doc.text(`Servicio: ${data.service}`,20,82);doc.text(`Total estimado: ${data.budget} EUR`,20,100);doc.save(`presupuesto-neotech-${data.name.toLowerCase().replace(/\s+/g,'-')}.pdf`)}
 async function submitQuote(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('loading');const form=new FormData(e.currentTarget);const hours=Number(form.get('hours')||0);const data={name:String(form.get('name')||'').trim(),email:String(form.get('email')||'').trim(),company:String(form.get('company')||'').trim(),service,hours,notes:String(form.get('notes')||'').trim(),budget:hours*rates[service]};try{const saved=await saveQuote(data);if(saved.error)throw saved.error;const code=saved.data?.clientCode||'pendiente';emailjs.init({publicKey:EMAILJS_PUBLIC_KEY});const payload={to_email:data.email,client_name:data.name,company:data.company,service:data.service,hours:data.hours,budget:`${data.budget}€`,notes:data.notes,client_code:code,admin_email:ADMIN_EMAIL,subject:'Tu solicitud de NeoTech ZGZ'};await emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_TEMPLATE_ID,payload);await emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_TEMPLATE_ID,{...payload,to_email:ADMIN_EMAIL,subject:`NUEVA SOLICITUD: ${data.name}`});await downloadQuote(data);setStatus('success')}catch{setStatus('error')}}
 async function submitContact(e:FormEvent<HTMLFormElement>){e.preventDefault();setContactStatus('loading');const f=new FormData(e.currentTarget);try{emailjs.init({publicKey:EMAILJS_PUBLIC_KEY});await emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_TEMPLATE_ID,{to_email:ADMIN_EMAIL,client_name:f.get('name'),reply_to:f.get('email'),message:f.get('message'),subject:'Nuevo contacto NeoTech ZGZ'});setContactStatus('success');e.currentTarget.reset()}catch{setContactStatus('error')}}
 const nav=[['servicios','Servicios'],['planes','Planes'],['proyectos','Proyectos'],['seguimiento','Seguimiento'],['contacto','Contacto']]
 return <main className={`site theme-${theme}`}><div className="sr-only" aria-live="polite">Los estados, errores y confirmaciones se muestran por texto.</div>{booting&&<div className="boot-screen" aria-label="Cargando NeoTech"><span>NEOTECH / ZGZ</span></div>}<header className="site-header"><nav><a href="#inicio" className="brand"><span className="brand-mark">N</span><span>NeoTech <em>ZGZ</em></span></a><div className="desktop-nav">{nav.map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}<div className="theme-picker" role="group" aria-label="Modo de color"><Palette size={15}/><button aria-label="Tema noche" aria-pressed={theme==='night'} className="theme-dot theme-night" onClick={()=>setTheme('night')}/><button aria-label="Tema blanco" aria-pressed={theme==='light'} className="theme-dot theme-light" onClick={()=>setTheme('light')}/></div><a className="button button-quiet" href="/login">Acceder</a><a className="button button-primary" href="/register">Crear cuenta</a></div><button className="menu-button" aria-label="Abrir menú" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></nav>{mobile&&<div className="mobile-nav">{nav.map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMobile(false)}>{label}</a>)}<div className="mobile-actions"><button aria-label="Tema noche" onClick={()=>setTheme('night')}>Negro</button><button aria-label="Tema blanco" onClick={()=>setTheme('light')}>Blanco</button><a href="/login">Acceder</a><a href="/register">Crear cuenta</a></div></div>}</header>
 <section id="inicio" className="hero"><div className="hero-copy"><p className="eyebrow">Sistemas · soporte · desarrollo</p><h1>Tecnología clara para negocios que quieren avanzar.</h1><p className="lede">Soporte IT, desarrollo web y consultoría para resolver problemas reales sin complicar lo importante.</p><div className="hero-actions"><a className="button button-primary" href="#servicios">Ver servicios <ArrowRight size={16}/></a><button className="button button-quiet" onClick={()=>quote()}>Solicitar presupuesto</button></div><div className="proof"><span><strong>6+</strong> años de experiencia</span><span><strong>24/7</strong> disponibilidad</span><span><strong>5+</strong> proyectos entregados</span></div></div><div className="hero-panel"><div className="panel-label">Cómo trabajamos</div>{['Escuchamos el problema','Proponemos una solución simple','La dejamos funcionando'].map((item,i)=><div className="process-row" key={item}><span>0{i+1}</span><p>{item}</p><Check size={16}/></div>)}<a href="#contacto" className="text-link">Hablemos de tu proyecto <ArrowRight size={16}/></a></div></section>
 <Section id="servicios" eyebrow="01 / Servicios" title="Soluciones que entiendes y puedes usar."><div className="service-grid">{services.map(([title,desc,price,unit,Icon])=><article className="service-card" key={title}><Icon size={21}/><h3>{title}</h3><p>{desc}</p><div><strong>{price}</strong><small> / {unit}</small></div><button className="text-link" onClick={()=>quote(title)}>Solicitar <ArrowRight size={15}/></button></article>)}</div></Section>
 <Section id="planes" eyebrow="02 / Soporte continuo" title="Acompañamiento sin letra pequeña."><div className="plan-grid">{plans.map(([name,price,features],i)=><article className={`plan-card ${i===1?'featured':''}`} key={name}><p className="plan-name">{name}</p><strong>{price}<small> /mes</small></strong><ul>{features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><button className={`button ${i===1?'button-primary':'button-quiet'}`} onClick={()=>quote(`Plan ${name}`)}>Elegir plan</button></article>)}</div></Section>
 <Section id="proyectos" eyebrow="03 / Casos reales" title="Trabajo pensado para personas reales."><div className="project-grid">{projects.map(([name,url,cat,place,desc])=><article className="project-card" key={name}><span className="project-index">0{projects.indexOf(projects.find(p=>p[0]===name)!)+1}</span><p>{cat}</p><h3>{name}</h3><span>{desc}</span><small><MapPin size={14}/>{place}</small><a href={`https://${url}`} target="_blank" rel="noreferrer" aria-label={`Ver ${name}`}>Visitar proyecto <ExternalLink size={14}/></a></article>)}</div></Section>
 <TrackingPanel/>
 <Section id="contacto" eyebrow="04 / Contacto" title="Cuéntame qué necesitas."><div className="contact-grid"><div><p className="lede">Una conversación breve puede convertir un problema técnico en un siguiente paso claro.</p><div className="contact-list"><a href="mailto:larbimhed260796@gmail.com"><Mail size={17}/>larbimhed260796@gmail.com</a><a href="tel:+34684798569"><Phone size={17}/>+34 684 798 569</a></div></div><form className="form-card" onSubmit={submitContact}><div className="form-grid"><input required name="name" placeholder="Nombre"/><input required name="email" type="email" placeholder="Email"/></div><textarea required name="message" rows={5} placeholder="¿En qué podemos ayudarte?"/><button className="button button-primary" disabled={contactStatus==='loading'}><Send size={15}/>{contactStatus==='loading'?'Enviando…':contactStatus==='success'?'Mensaje enviado':contactStatus==='error'?'Reintentar':'Enviar mensaje'}</button></form></div></Section>
 <footer><div><a href="#inicio" className="brand"><span className="brand-mark">N</span><span>NeoTech <em>ZGZ</em></span></a><p>Soporte, desarrollo y consultoría IT desde Zaragoza.</p></div><div className="footer-links"><a href="/login">Acceder</a><a href="/register">Crear cuenta</a><a href="https://www.linkedin.com/in/mohammed-jassem-larbi-26098b271/" target="_blank" rel="noreferrer">LinkedIn</a></div></footer>
 {open&&<div className="modal-backdrop" role="dialog" aria-modal="true"><div className="quote-modal"><button className="modal-close" aria-label="Cerrar" onClick={()=>setOpen(false)}><X/></button>{status==='success'?<div className="success-state"><Check size={32}/><h2>Solicitud recibida</h2><p>Hemos generado tu presupuesto y enviado el resumen por email.</p></div>:<><p className="eyebrow">Presupuesto</p><h2>Cuéntame los detalles.</h2><form onSubmit={submitQuote}><input required name="name" placeholder="Nombre completo"/><input required name="email" type="email" placeholder="Email"/><input name="company" placeholder="Empresa / negocio (opcional)"/><select value={service} onChange={e=>setService(e.target.value)}><option>Soporte Remoto</option><option>Soporte Presencial</option><option>Desarrollo Web</option><option>Consultoría IT</option><option>Análisis de Sistemas</option></select><input required name="hours" type="number" min="1" placeholder="Horas estimadas"/><textarea required name="notes" rows={4} placeholder="Descripción del proyecto"/>{status==='error'&&<p className="form-message error">No se pudo completar la solicitud. Revisa los datos e inténtalo de nuevo.</p>}<button className="button button-primary" disabled={status==='loading'}><FileDown size={16}/>{status==='loading'?'Generando…':'Generar presupuesto'}</button></form></>}</div></div>}</main>
}
