'use client'

import { FormEvent, useEffect, useRef, useState, type CSSProperties, type ReactNode } from 'react'
import emailjs from '@emailjs/browser'
import jsPDF from 'jspdf'
import { ArrowRight, Check, Code2, ExternalLink, FileDown, Mail, MapPin, Menu, Phone, Send, Server, ShieldCheck, Sparkles, X, Zap } from 'lucide-react'
import { saveQuote } from '@/lib/supabase'

const EMAILJS_PUBLIC_KEY = process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY || 'Kes0uwCNdJkfPTi2B'
const EMAILJS_SERVICE_ID = process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID || 'service_qs5srkr'
const EMAILJS_TEMPLATE_ID = process.env.NEXT_PUBLIC_EMAILJS_TEMPLATE_ID || 'template_4me8r7g'
const ADMIN_EMAIL = 'larbimhed260796@gmail.com'

const rates: Record<string, number> = { 'Soporte Remoto': 30, 'Soporte Presencial': 45, 'Desarrollo Web': 350, 'Consultoría IT': 60, 'Análisis de Sistemas': 55, 'Plan STARTER': 49, 'Plan PROFESSIONAL': 89, 'Plan ENTERPRISE': 199 }
const projects: [string, string, string, string, string, string][] = [['Ella\'s Details','ellasdetails.netlify.app','Landing E-commerce','Dayton, Ohio','Diseño web para decoraciones, ramos y desayunos','🌸'],['You Portfolio Danza','youdance.netlify.app','Portfolio','Universidad de Lyon','Sitio trilingüe para bailarina profesional','💃'],['Mariano Patines ZGZ','zgzpatinesnano.netlify.app','Local Business','Zaragoza, España','Web con click-to-call para tienda local','⚡'],['ASOCEMIR','asocemir.netlify.app','Asociación Cultural','Zaragoza / Argentina','Sitio bilingüe para asociación árabe-aragonesa','🕌'],['Streaming Twitch','twitch.tv/twich_perita23','Gaming / Streaming','Online','Canal con integración de API de Twitch','🎥']]
const services = [['Soporte Remoto','Asistencia técnica remota, troubleshooting y optimización','30€','hora',Server],['Soporte Presencial','Visita a domicilio o empresa, instalación y mantenimiento','45€','hora',MapPin],['Desarrollo Web','Landing pages, webs profesionales y e-commerce básico','350€','desde',Code2],['Consultoría IT','Análisis de sistemas, recomendaciones y planning','60€','hora',Sparkles],['Análisis de Sistemas','Auditoría IT, diagnóstico y reporte personalizado','55€','hora',ShieldCheck]] as const
const plans: [string, string, string[]][] = [['STARTER','49€',['3 horas de soporte / mes','Email + teléfono','Respuesta en 24h']],['PROFESSIONAL','89€',['8 horas de soporte / mes','1 visita presencial / mes','Email + teléfono + WhatsApp','Respuesta en 12h']],['ENTERPRISE','199€',['Soporte 24/7','Visitas ilimitadas','Email + teléfono + WhatsApp + Priority','SLA 99.99%','Consultoría incluida']]]

function Section({ id, kicker, title, children }: { id: string; kicker: string; title: string; children: ReactNode }) { return <section id={id} className="section reveal-section mx-auto max-w-6xl px-5 py-24"><div className="mb-12"><p className="mono mb-3 text-xs uppercase tracking-[.28em] text-cyan-400">{kicker}</p><h2 className="text-4xl font-bold tracking-tight text-white md:text-5xl">{title}</h2></div>{children}</section> }

function DoomArena() {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const [score, setScore] = useState(0)
  const [running, setRunning] = useState(false)
  useEffect(() => {
    if (!running) return
    const canvas = canvasRef.current; const ctx = canvas?.getContext('2d'); if (!canvas || !ctx) return
    const keys = new Set<string>(); let animation = 0; let frame = 0; let localScore = score
    const enemies = Array.from({ length: 7 }, (_, i) => ({ x: 60 + i * 70, y: 50 + (i % 3) * 34, alive: true }))
    const resize = () => { canvas.width = canvas.clientWidth * devicePixelRatio; canvas.height = canvas.clientHeight * devicePixelRatio; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0) }
    const draw = () => { const w = canvas.clientWidth, h = canvas.clientHeight; frame++; ctx.fillStyle = '#130707'; ctx.fillRect(0, 0, w, h); ctx.strokeStyle = '#4d1710'; for (let x = 0; x < w; x += 32) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke() } for (let y = 0; y < h; y += 32) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke() } enemies.forEach((enemy, i) => { if (!enemy.alive) return; enemy.x += Math.sin(frame / 18 + i) * .4; ctx.fillStyle = '#d83b20'; ctx.fillRect(enemy.x - 12, enemy.y - 14, 24, 28); ctx.fillStyle = '#ffb52e'; ctx.fillRect(enemy.x - 8, enemy.y - 4, 5, 5); ctx.fillRect(enemy.x + 3, enemy.y - 4, 5, 5); ctx.fillStyle = '#6b120d'; ctx.fillRect(enemy.x - 8, enemy.y + 7, 16, 4) }); ctx.fillStyle = '#f59e0b'; ctx.fillRect(w / 2 - 35, h - 48, 70, 48); ctx.fillStyle = '#30100b'; ctx.fillRect(w / 2 - 8, h - 38, 16, 38); ctx.fillStyle = '#f2d18a'; ctx.font = '12px monospace'; ctx.fillText('WASD / FLECHAS · ESPACIO: DISPARAR', 14, 22); animation = requestAnimationFrame(draw) }
    const onKey = (event: KeyboardEvent) => { keys.add(event.key.toLowerCase()); if (event.code === 'Space') { const target = enemies.find(enemy => enemy.alive); if (target) { target.alive = false; localScore += 100; setScore(localScore) } event.preventDefault() } }
    const onUp = (event: KeyboardEvent) => keys.delete(event.key.toLowerCase()); window.addEventListener('keydown', onKey); window.addEventListener('keyup', onUp); window.addEventListener('resize', resize); resize(); draw(); return () => { cancelAnimationFrame(animation); window.removeEventListener('keydown', onKey); window.removeEventListener('keyup', onUp); window.removeEventListener('resize', resize) }
  }, [running])
  return <section id="doom" className="doom-zone border-t border-red-500/20 px-5 py-24"><div className="mx-auto max-w-6xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mono text-xs uppercase tracking-[.3em] text-orange-400">07 / BONUS PROTOCOL</p><h2 className="mt-3 text-4xl font-bold text-orange-100 md:text-6xl">DOOM // FIREWALL ARENA</h2><p className="mt-3 max-w-xl text-slate-400">Un minijuego arcade inspirado en los shooters clásicos. Activa el sistema, elimina las amenazas y consigue puntos.</p></div><div className="mono border border-orange-500/30 bg-black/30 px-5 py-3 text-orange-300">SCORE: {String(score).padStart(4, '0')}</div></div><div className="overflow-hidden rounded-2xl border border-red-500/40 bg-black p-2 shadow-[0_0_60px_rgba(239,68,68,.15)]"><canvas ref={canvasRef} className="doom-canvas h-[360px] w-full" aria-label="Arena arcade interactiva" /></div><div className="mt-5 flex flex-wrap items-center gap-4"><button onClick={() => { setScore(0); setRunning(true) }} className="doom-button rounded-lg px-5 py-3 font-bold">{running ? 'REINICIAR ARENA' : 'INICIAR DOOM'}</button><p className="mono text-xs text-orange-200/70">ESPACIO para disparar · Recarga automática</p></div></div></section>
}

export default function Home() {
  const [open, setOpen] = useState(false); const [mobile, setMobile] = useState(false); const [service, setService] = useState('Soporte Remoto'); const [status, setStatus] = useState('idle'); const [contactStatus, setContactStatus] = useState('idle'); const [booting, setBooting] = useState(true)
  useEffect(() => { const timer = window.setTimeout(() => setBooting(false), 1100); return () => window.clearTimeout(timer) }, [])
  const quote = (title = 'Solicitar presupuesto') => { setService(title); setOpen(true) }
  async function downloadQuote(data: { name: string; email: string; company: string; service: string; hours: number; notes: string; budget: number }) {
    const doc = new jsPDF(); doc.setFillColor(8,12,20); doc.rect(0,0,210,297,'F'); doc.setTextColor(226,232,240); doc.setFontSize(24); doc.text('NeoTech ZGZ',20,28); doc.setFontSize(10); doc.setTextColor(0,212,255); doc.text('SOLUCIONES IT · ZARAGOZA',20,37); doc.setDrawColor(0,212,255); doc.line(20,45,190,45); doc.setTextColor(226,232,240); doc.setFontSize(14); doc.text('Presupuesto personalizado',20,65); doc.setFontSize(10); doc.text(`Fecha: ${new Date().toLocaleDateString('es-ES')}`,20,78); doc.text(`Validez: 30 días`,20,86); doc.text(`Cliente: ${data.name}`,20,104); doc.text(`Email: ${data.email}`,20,112); if (data.company) doc.text(`Empresa: ${data.company}`,20,120); doc.text(`Servicio: ${data.service}`,20,140); doc.text(`Horas / unidades: ${data.hours}`,20,148); doc.setFontSize(20); doc.setTextColor(0,212,255); doc.text(`Total estimado: ${data.budget} EUR`,20,170); doc.setFontSize(10); doc.setTextColor(145,160,181); doc.text('Condiciones: pago tras confirmación del servicio. Presupuesto sujeto a alcance final.',20,195); doc.text('Contacto: larbimhed260796@gmail.com · +34 684 798 569',20,215); doc.save(`presupuesto-neotech-${data.name.toLowerCase().replace(/\s+/g,'-')}.pdf`)
  }
  async function submitQuote(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setStatus('loading'); const form = new FormData(e.currentTarget); const data = { name: String(form.get('name') || ''), email: String(form.get('email') || ''), company: String(form.get('company') || ''), service, hours: Math.max(1, Number(form.get('hours') || 1)), notes: String(form.get('notes') || ''), budget: Math.max(1, Number(form.get('hours') || 1)) * rates[service] }; try { const saved = await saveQuote(data); if (saved?.error) console.warn('[v0] Quote persistence unavailable:', saved.error.message); emailjs.init({ publicKey: EMAILJS_PUBLIC_KEY }); const payload = { to_email: data.email, client_name: data.name, company: data.company, service: data.service, hours: data.hours, budget: `${data.budget}€`, notes: data.notes, admin_email: ADMIN_EMAIL, subject: 'Tu presupuesto de NeoTech ZGZ' }; const result = await emailjs.send(EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, payload); if (result.status >= 400) throw new Error('EmailJS no pudo enviar el mensaje'); await emailjs.send(EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, { ...payload, to_email: ADMIN_EMAIL, subject: `NUEVO PRESUPUESTO: ${data.name}` }); downloadQuote(data); setStatus('success') } catch (error) { console.error('[v0] Quote error:', error); downloadQuote(data); setStatus('error') } }
  async function submitContact(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setContactStatus('loading'); const form = new FormData(e.currentTarget); try { emailjs.init({ publicKey: EMAILJS_PUBLIC_KEY }); const result = await emailjs.send(EMAILJS_SERVICE_ID, EMAILJS_TEMPLATE_ID, { to_email: ADMIN_EMAIL, client_name: form.get('name'), reply_to: form.get('email'), message: form.get('message'), subject: 'Nuevo contacto NeoTech ZGZ' }); if (result.status >= 400) throw new Error('EmailJS error'); setContactStatus('success'); e.currentTarget.reset() } catch { setContactStatus('error') } }
  return <main className="min-h-screen overflow-hidden">{booting && <div className="boot-screen" aria-label="Cargando NeoTech ZGZ"><div className="boot-core"/><div className="boot-particles">{Array.from({length: 18}, (_, i) => <i key={i} style={{'--i': i} as CSSProperties}/>)}</div><p className="mono boot-label">NEOTECH // SYSTEM ONLINE</p></div>}<header className="fixed inset-x-0 top-0 z-40 border-b border-cyan-400/10 bg-[#080c14]/85 backdrop-blur-xl"><nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><a href="#inicio" className="flex items-center gap-3 font-bold text-white"><span className="grid size-9 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><Zap /></span>NeoTech <span className="text-cyan-300">ZGZ</span></a><div className="hidden items-center gap-5 text-sm text-slate-400 lg:flex">{[['inicio','Inicio'],['experiencia','Experiencia'],['proyectos','Proyectos'],['servicios','Servicios'],['planes','Planes'],['certificaciones','Certificaciones'],['contacto','Contacto']].map(([id,label])=><a key={id} href={`#${id}`} className="transition hover:text-cyan-300">{label}</a>)}<button onClick={()=>quote()} className="cta rounded-lg px-4 py-2 text-xs font-bold">Solicitar presupuesto</button></div><button className="lg:hidden" onClick={()=>setMobile(!mobile)} aria-label="Abrir menú"><Menu className="text-cyan-300"/></button></nav>{mobile&&<div className="border-t border-cyan-400/10 bg-[#080c14] px-5 py-4 lg:hidden">{['inicio','experiencia','proyectos','servicios','planes','certificaciones','contacto'].map(id=><a key={id} onClick={()=>setMobile(false)} href={`#${id}`} className="block py-2 text-sm capitalize text-slate-300">{id}</a>)}</div>}</header>
    <section id="inicio" className="grid-bg relative flex min-h-[760px] items-center px-5 pb-16 pt-36"><div className="orb left-1/4 top-24 size-72 bg-cyan-400"/><div className="orb bottom-10 right-10 size-80 bg-violet-600"/><div className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[1.1fr_.9fr]"><div className="relative"><p className="mono mb-6 text-xs uppercase tracking-[.3em] text-cyan-300">NEOTECH / ZGZ · DIGITAL SYSTEMS</p><h1 className="max-w-4xl text-5xl font-bold leading-[1.04] tracking-tight text-white md:text-7xl">Soluciones IT profesionales, <span className="gradient-text">soporte 24/7</span> y consultoría enterprise</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-400">6+ años transformando negocios con tecnología fiable, humana y preparada para crecer.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#servicios" className="cta inline-flex items-center gap-2 rounded-lg px-5 py-3 font-semibold">Ver servicios <ArrowRight size={17}/></a><button onClick={()=>quote()} className="rounded-lg border border-cyan-300/30 px-5 py-3 font-semibold text-slate-100 transition hover:border-cyan-300 hover:bg-cyan-300/10">Solicitar presupuesto</button></div><div className="mt-14 grid max-w-2xl grid-cols-2 gap-6 border-t border-cyan-400/15 pt-7 md:grid-cols-4">{[['6+','Años experiencia'],['24/7','Disponible'],['100%','Satisfacción'],['5+','Proyectos']].map(([n,l])=><div key={l}><strong className="text-2xl text-white">{n}</strong><p className="mt-1 text-xs text-slate-500">{l}</p></div>)}</div></div><div className="glass relative rounded-3xl p-6 md:p-8"><div className="mb-8 flex items-center justify-between"><span className="mono text-xs text-cyan-300">SYSTEM_STATUS</span><span className="flex items-center gap-2 text-xs text-emerald-300"><i className="size-2 rounded-full bg-emerald-400"/>Operativo</span></div>{['Diagnóstico de sistemas','Soporte remoto y presencial','Desarrollo web escalable','Consultoría estratégica'].map((x,i)=><div key={x} className="mb-3 rounded-xl bg-slate-950/70 p-4 text-sm text-slate-300"><span className="mr-3 text-cyan-300">0{i+1}</span>{x}<span className="float-right text-emerald-400">OK</span></div>)}</div></div></section>
    <Section id="experiencia" kicker="01 / TRAYECTORIA" title="Mi trayectoria"><div className="grid gap-4 md:grid-cols-3">{[['2019 — Actual','Analista de Sistemas','Freelance · NeoTech ZGZ'],['2019 — 2024','Técnico Soporte N1','Zaidan IT Solutions'],['2018','ASIR','IES Tiempos Modernos · Matrícula de Honor FCT UZ']].map(([date,title,desc])=><article className="glass rounded-2xl p-6" key={title}><span className="mono text-xs text-cyan-300">{date}</span><h3 className="mt-8 text-xl font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{desc}</p></article>)}</div></Section>
    <Section id="proyectos" kicker="02 / CASOS REALES" title="Proyectos que hablan por sí mismos"><div className="project-deck">{projects.map(([name,url,cat,place,desc,emoji])=><article key={name} className="glass group flex flex-col rounded-2xl p-6 transition hover:-translate-y-1 hover:border-cyan-300/40"><div className="flex items-start justify-between"><span className="text-4xl">{emoji}</span><span className="rounded-full border border-cyan-400/20 px-3 py-1 text-[10px] uppercase tracking-wider text-cyan-300">{cat}</span></div><h3 className="mt-7 text-xl font-semibold text-white">{name}</h3><a href={`https://${url}`} target="_blank" rel="noreferrer" className="mt-2 flex items-center gap-2 text-sm text-cyan-300 hover:underline">{url}<ExternalLink size={13}/></a><p className="mt-4 text-sm leading-6 text-slate-400">{desc}</p><p className="mt-auto flex items-center gap-2 pt-7 text-xs text-slate-500"><MapPin size={14}/>{place}</p></article>)}</div></Section>
    <Section id="servicios" kicker="03 / CAPACIDADES" title="Tecnología con impacto medible"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([title,desc,price,unit,Icon])=><article className="glass rounded-2xl p-6" key={title}><Icon className="text-cyan-300"/><h3 className="mt-6 text-xl font-semibold text-white">{title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-slate-400">{desc}</p><div className="mt-7 flex items-end justify-between"><div><span className="text-3xl font-bold text-white">{price}</span><span className="ml-1 text-xs text-slate-500">/{unit}</span></div><button onClick={()=>quote(title)} className="rounded-lg border border-cyan-400/25 px-3 py-2 text-xs text-cyan-300 hover:bg-cyan-400/10">Solicitar</button></div></article>)}</div></Section>
    <Section id="planes" kicker="04 / SOPORTE CONTINUO" title="Un plan para cada etapa"><div className="grid gap-5 lg:grid-cols-3">{plans.map(([name,price,features],i)=><article className={`glass relative rounded-2xl p-7 ${i===1?'border-cyan-300/60 shadow-[0_0_40px_rgba(0,212,255,.1)]':''}`} key={name}>{i===1&&<span className="absolute -top-3 right-6 rounded-full bg-cyan-300 px-3 py-1 text-xs font-bold text-[#080c14]">RECOMENDADO</span>}<p className="mono text-xs tracking-widest text-cyan-300">{name}</p><div className="mt-5 text-5xl font-bold text-white">{price}<span className="text-sm font-normal text-slate-500"> /mes</span></div><ul className="mt-8 flex flex-col gap-4 text-sm text-slate-300">{features.map(f=><li className="flex gap-3" key={f}><Check className="shrink-0 text-emerald-400" size={18}/>{f}</li>)}</ul><button onClick={()=>quote(`Plan ${name}`)} className="mt-9 w-full rounded-lg border border-cyan-400/25 py-3 text-sm font-semibold text-cyan-200 transition hover:bg-cyan-400/10">Contratar ahora</button></article>)}</div></Section>
    <Section id="certificaciones" kicker="05 / FORMACIÓN" title="Certificaciones & formación"><div className="grid gap-4 md:grid-cols-2">{[['ASIR','IES Tiempos Modernos · 2018','Matrícula de Honor · FCT sobresaliente'],['Analista y Diseñador de Sistemas','Edutin Academy · 2019','Certificado profesional'],['Licenciatura en Física Teórica','Aix-Marseille University · 2023+','Estudios universitarios avanzados'],['Skills IT adicionales','Certificaciones prácticas','Soporte técnico · Administración · Consultoría']].map(([a,b,c])=><div key={a} className="glass rounded-2xl p-6"><div className="flex gap-4"><div className="grid size-11 shrink-0 place-items-center rounded-xl bg-violet-500/15 text-violet-300"><ShieldCheck/></div><div><h3 className="font-semibold text-white">{a}</h3><p className="mt-1 text-sm text-cyan-300">{b}</p><p className="mt-3 text-sm text-slate-400">{c}</p></div></div></div>)}</div><a className="mt-7 inline-flex items-center gap-2 text-sm text-cyan-300 hover:underline" href="https://www.linkedin.com/in/mohammed-jassem-larbi-26098b271/" target="_blank" rel="noreferrer">Ver perfil completo en LinkedIn <ExternalLink size={14}/></a></Section>
    <Section id="contacto" kicker="06 / HABLEMOS" title="¿Listo para comenzar?"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="max-w-md text-lg leading-8 text-slate-400">Contacta conmigo para una consulta sin compromiso. Una conversación clara es el primer paso para una solución mejor.</p><div className="mt-8 flex flex-col gap-4 text-sm"><a className="flex gap-3 text-slate-300 hover:text-cyan-300" href="mailto:larbimhed260796@gmail.com"><Mail className="text-cyan-300"/>larbimhed260796@gmail.com</a><a className="flex gap-3 text-slate-300 hover:text-cyan-300" href="tel:+34684798569"><Phone className="text-cyan-300"/>+34 684 798 569</a><a className="flex gap-3 text-slate-300 hover:text-cyan-300" href="https://wa.me/34684798569">WhatsApp · Instagram · Facebook</a></div></div><form className="glass rounded-2xl p-6" onSubmit={submitContact}><div className="grid gap-4 sm:grid-cols-2"><input required name="name" placeholder="Nombre" className="field"/><input required name="email" type="email" placeholder="Email" className="field"/></div><textarea required name="message" placeholder="¿En qué podemos ayudarte?" rows={5} className="field mt-4 w-full"/><button disabled={contactStatus==='loading'} className="cta mt-4 inline-flex items-center gap-2 rounded-lg px-5 py-3 text-sm font-semibold"><Send size={15}/>{contactStatus==='loading'?'Enviando...':contactStatus==='success'?'Mensaje enviado':contactStatus==='error'?'Reintentar':'Enviar mensaje'}</button></form></div></Section>
    <DoomArena />
    <footer className="border-t border-cyan-400/10 px-5 py-10"><div className="mx-auto flex max-w-6xl flex-col gap-6 text-sm text-slate-500 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold text-slate-300">NeoTech ZGZ</p><p className="mt-2">© 2026 NeoTech ZGZ. Todos los derechos reservados.</p></div><p>Diseñado accesible para daltónicos y personas sordas</p><div className="flex gap-4"><a href="#servicios" className="hover:text-cyan-300">Servicios</a><a href="#planes" className="hover:text-cyan-300">Planes</a><a href="https://instagram.com/_neotechzgz" className="hover:text-cyan-300">Instagram</a><a href="https://facebook.com/neotechzgz" target="_blank" rel="noreferrer" className="hover:text-cyan-300">Facebook</a><a href="https://www.linkedin.com/in/mohammed-jassem-larbi-26098b271/" target="_blank" rel="noreferrer" className="hover:text-cyan-300">LinkedIn</a></div></div></footer>
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-5 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="glass max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl p-6 md:p-8"><div className="flex items-start justify-between"><div><p className="mono text-xs text-cyan-300">QUOTE_GENERATOR</p><h2 className="mt-2 text-2xl font-bold text-white">Solicitar presupuesto</h2></div><button onClick={()=>setOpen(false)} aria-label="Cerrar"><X className="text-slate-400"/></button></div>{status==='success'?<div className="py-16 text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-emerald-400/15 text-emerald-300"><Check/></div><h3 className="mt-5 text-xl font-semibold text-white">Presupuesto generado</h3><p className="mt-2 text-sm text-slate-400">El PDF se ha descargado y hemos enviado el resumen por email.</p></div>:<form onSubmit={submitQuote} className="mt-7 flex flex-col gap-4"><input required name="name" placeholder="Nombre completo" className="field"/><input required name="email" type="email" placeholder="Email" className="field"/><input name="company" placeholder="Empresa / negocio (opcional)" className="field"/><select value={service} onChange={e=>setService(e.target.value)} className="field"><option>Soporte Remoto</option><option>Soporte Presencial</option><option>Desarrollo Web</option><option>Consultoría IT</option><option>Análisis de Sistemas</option></select><input required name="hours" type="number" min="1" placeholder="Horas estimadas" className="field"/><textarea required name="notes" rows={4} placeholder="Descripción del proyecto y notas" className="field"/>{status==='error'&&<p className="text-sm text-amber-300">PDF descargado, pero EmailJS o Supabase no están configurados correctamente.</p>}<button disabled={status==='loading'} className="cta inline-flex items-center justify-center gap-2 rounded-lg py-3 font-semibold"><FileDown size={16}/>{status==='loading'?'Generando...':'Generar presupuesto PDF'}</button><p className="text-center text-xs text-slate-500">Se guarda el registro en Supabase y se envía el resumen mediante EmailJS.</p></form>}</div></div>}</main>
}
