'use client'

import { FormEvent, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function RegisterPage() {
  const router = useRouter(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); setMessage(''); const { data, error } = await createClient().auth.signUp({ email, password, options: { emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL ?? `${window.location.origin}/auth/callback` } }); if (error) setError(error.message.toLowerCase().includes('password') ? 'La contraseña debe tener al menos 6 caracteres.' : 'No se pudo crear la cuenta. Revisa los datos e inténtalo de nuevo.'); else if (data.session) router.replace('/'); else setMessage('Revisa tu email para confirmar la cuenta.'); setLoading(false) }
  return <main className="admin-shell min-h-screen px-5 py-20 text-white"><div className="admin-card mx-auto max-w-md rounded-sm p-8"><p className="mono text-xs tracking-[.3em] text-cyan-300">NEOTECH / IDENTITY</p><h1 className="mt-3 text-3xl font-bold">Crear cuenta</h1><p className="mt-3 text-sm text-slate-400">Regístrate para consultar tus solicitudes de forma privada.</p><form onSubmit={submit} className="mt-8 flex flex-col gap-4"><label className="text-sm text-slate-300">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="field mt-2 w-full" autoComplete="email" /></label><label className="text-sm text-slate-300">Contraseña<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="field mt-2 w-full" autoComplete="new-password" /></label>{error&&<p role="alert" className="text-sm text-amber-300">{error}</p>}{message&&<p role="status" className="text-sm text-emerald-300">{message}</p>}<button disabled={loading} className="cta rounded-lg py-3 font-semibold">{loading?'Creando...':'Crear cuenta'}</button></form><p className="mt-6 text-sm text-slate-400">¿Ya tienes cuenta? <a className="text-cyan-300 hover:underline" href="/login">Iniciar sesión</a></p></div></main>
}
